### ISSUE TITLE
Log Details (WARNING)

### ISSUE THREAD

**Issue by tarheelz** [dolezsa/thermal_comfort#176] opened 2022-07-08 22:58 UTC
`Temperature sensor sensor.xxx_dewpoint (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) does not inherit SensorEntity, this will be unsupported in Home Assistant Core 2022.7.Please report it to the custom component author.`

**Comment by rautesamtr** [comment] 2022-07-09 09:10
What version of thermal comfort are you using?

**Comment by rautesamtr** [comment] 2022-08-08 10:11
Since no further info was provided and i can't reproduce this i am closing this for now.

**Closed by rautesamtr** 2022-08-08 10:11 UTC
